// Rajasthan districts in Hindi
export const RAJASTHAN_DISTRICTS = [
  'सभी जिले',
  'जयपुर',
  'जोधपुर',
  'कोटा',
  'बीकानेर',
  'अजमेर',
  'उदयपुर',
  'भरतपुर',
  'अलवर',
  'सीकर',
  'चुरू',
  'बूंदी',
  'झालावाड़',
  'टोंक',
  'सवाई माधोपुर',
  'करौली',
  'धौलपुर',
  'बारां',
  'बांसवाड़ा',
  'डूंगरपुर',
  'प्रतापगढ़',
  'राजसमंद',
  'भीलवाड़ा',
  'चित्तौड़गढ़',
  'पाली',
  'नागौर',
  'जालौर',
  'सिरोही',
  'बाड़मेर',
  'जैसलमेर',
  'हनुमानगढ़',
  'गंगानगर',
  'श्रीगंगानगर'
];

// District slugs for routing
export const DISTRICT_SLUGS = {
  'सभी जिले': 'all',
  'जयपुर': 'jaipur',
  'जोधपुर': 'jodhpur',
  'कोटा': 'kota',
  'बीकानेर': 'bikaner',
  'अजमेर': 'ajmer',
  'उदयपुर': 'udaipur',
  'भरतपुर': 'bharatpur',
  'अलवर': 'alwar',
  'सीकर': 'sikar',
  'चुरू': 'churu',
  'बूंदी': 'bundi',
  'झालावाड़': 'jhalawar',
  'टोंक': 'tonk',
  'सवाई माधोपुर': 'sawai-madhopur',
  'करौली': 'karauli',
  'धौलपुर': 'dholpur',
  'बारां': 'baran',
  'बांसवाड़ा': 'banswara',
  'डूंगरपुर': 'dungarpur',
  'प्रतापगढ़': 'pratapgarh',
  'राजसमंद': 'rajsamand',
  'भीलवाड़ा': 'bhilwara',
  'चित्तौड़गढ़': 'chittorgarh',
  'पाली': 'pali',
  'नागौर': 'nagaur',
  'जालौर': 'jalor',
  'सिरोही': 'sirohi',
  'बाड़मेर': 'barmer',
  'जैसलमेर': 'jaisalmer',
  'हनुमानगढ़': 'hanumangarh',
  'गंगानगर': 'ganganagar',
  'श्रीगंगानगर': 'sri-ganganagar'
};

