// Rajasthan districts in Hindi
export const RAJASTHAN_DISTRICTS = [
  'सभी जिले',
  'अजमेर',
  'अलवर',
  'बांसवाड़ा',
  'बाड़मेर',
  'भरतपुर',
  'भीलवाड़ा',
  'बीकानेर',
  'बूंदी',
  'चित्तौड़गढ़',
  'चूरू',
  'दौसा',
  'धौलपुर',
  'डूंगरपुर',
  'हनुमानगढ़',
  'जयपुर',
  'जैसलमेर',
  'जालौर',
  'झालावाड़',
  'झुंझुनूं',
  'जोधपुर',
  'करौली',
  'कोटा',
  'नागौर',
  'पाली',
  'प्रतापगढ़',
  'राजसमंद',
  'सवाई माधोपुर',
  'सीकर',
  'सिरोही',
  'टोंक',
  'उदयपुर',
  'श्रीगंगानगर'
];

// District slugs for routing
export const DISTRICT_SLUGS = {
  'सभी जिले': 'all',
  'अजमेर': 'ajmer',
  'अलवर': 'alwar',
  'बांसवाड़ा': 'banswara',
  'बाड़मेर': 'barmer',
  'भरतपुर': 'bharatpur',
  'भीलवाड़ा': 'bhilwara',
  'बीकानेर': 'bikaner',
  'बूंदी': 'bundi',
  'चित्तौड़गढ़': 'chittorgarh',
  'चूरू': 'churu',
  'दौसा': 'dausa',
  'धौलपुर': 'dholpur',
  'डूंगरपुर': 'dungarpur',
  'हनुमानगढ़': 'hanumangarh',
  'जयपुर': 'jaipur',
  'जैसलमेर': 'jaisalmer',
  'जालौर': 'jalor',
  'झालावाड़': 'jhalawar',
  'झुंझुनूं': 'jhunjhunu',
  'जोधपुर': 'jodhpur',
  'करौली': 'karauli',
  'कोटा': 'kota',
  'नागौर': 'nagaur',
  'पाली': 'pali',
  'प्रतापगढ़': 'pratapgarh',
  'राजसमंद': 'rajsamand',
  'सवाई माधोपुर': 'sawai-madhopur',
  'सीकर': 'sikar',
  'सिरोही': 'sirohi',
  'टोंक': 'tonk',
  'उदयपुर': 'udaipur',
  'श्रीगंगानगर': 'sri-ganganagar'
};

